# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev366+g02d9a87.d20230820'
__version_tuple__ = version_tuple = (0, 1, 'dev366', 'g02d9a87.d20230820')
