# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev337+g933b250.d20230313'
__version_tuple__ = version_tuple = (0, 1, 'dev337', 'g933b250.d20230313')
