# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev344+g6a98d74.d20230413'
__version_tuple__ = version_tuple = (0, 1, 'dev344', 'g6a98d74.d20230413')
