name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Check code with Flake8
        run: |
          flake8 protoSpaceJAM
